#spring.profiles.active = local
#spring.main.web-environment = true
server:
  port: 8081
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ams?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
      host: smtp.gmail.com
      port: 587
      username: rapatel1381@gmail.com
      password: R@hulgoti8128313138
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  data:
          elasticsearch:
              cluster-name: my-application
              cluster-nodes: localhost:9300
              properties:
                  path:
                      logs: build/elasticsearch/log
                      data: build/elasticsearch/data
# elasticsearch
elasticsearch:
  clustername: "my-application"
  host: "localhost"
  port: 9300

#logging
#logging:
#    level:
#        ROOT: INFO
#        com.ams: INFO
#logging:
#  config : "config/log4j2.xml"

#security:
#  authentication:
jwt:
  secret: "my-secret-token-to-change-in-production"
  # Token is valid 24 hours
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 2592000

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

ams:
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: ams@localhost
    base-url: http://127.0.0.1:8080
# Multipart Configuration
multipart:
  location: /Uploads
  maxFileSize: 100Mb
  maxRequestSize: 100Mb
  fileSizeThreshold: 10Mb